### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Aidan-The-Dev** [KartikeSingh/ms-prettify#1]
let value = convert(strings[i + 1].trim().toLowerCase());
                                                   ^

TypeError: Cannot read property 'trim' of undefined
    at C:\Users\ocean\Documents\Gemini\node_modules\ms-prettify\src\utility\toMS.js:19:52
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\ocean\Documents\Gemini\node_modules\ms-prettify\src\utility\toMS.js:12:13)
    at convertor (C:\Users\ocean\Documents\Gemini\node_modules\ms-prettify\src\index.js:17:44)
    at C:\Users\ocean\Documents\Gemini\index.js:72:14

**Comment by KartikeSingh** [comment]
Alright, it will be fixed in the new update
